# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Wizeline Backend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Frontend-ESLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install eslint package
        run: cd frontend && npm install eslint
      - name: Check ESLint rules
        run: cd frontend && npm run check-eslint-rules

  API-Testing:
    needs: Frontend-ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install npm dependencies
        run: cd backend && npm install
      - name: Run POSTMAN collection
        env:
          TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}
        run: cd backend && npm run test-todoist-api-ci
